### ISSUE TITLE
Overriding app.ErrorMiddleware has no effect

### ISSUE THREAD

**Issue by devboy** [gobuffalo/buffalo#1466] opened 2018-11-23 12:53 UTC
I have a buffalo.App for a JSON REST api.
Switching the `GO_ENV` to `production` causes all errors to be sent as HTML.
I changed the `app.ErrorMiddleware` to my custom one yet the `defaultErrorMiddleware` is still being called while the one I assigned is ignored.

**Comment by paganotoni** [comment] 2019-01-04 02:50
@devboy i tried to reproduce this with https://gist.github.com/paganotoni/a6d165e2a12447759cc9a68518b720a3 and it seems that i'm able to override the default error handlers even with GO_ENV=production.

Instead of changing the ErrorMiddleware i'm updating the error handlers, would this strategy work for you?.

**Comment by paganotoni** [comment] 2019-01-14 22:17
@devboy can i know the reasons to override the ErrorMiddleware and why using custom error handlers wont work for you ?

**Comment by sebd71** [comment] 2019-01-29 21:45
I would say that ErrorMiddleware cannot be overriding due to invalid if statement in app.go (line 55) : 
https://github.com/gobuffalo/buffalo/blob/78d649ad376f5b9da360e89dce5c1d31cf2772ba/app.go#L55

```
-	if a.ErrorMiddleware != nil {
+	if opts.ErrorMiddleware != nil {
```

If i'm correct, let me know if you want that I submit a pull request.

**Comment by sebd71** [comment] 2019-01-29 22:20
I don't understand the goal of if statement of app.go line 55
https://github.com/gobuffalo/buffalo/blob/78d649ad376f5b9da360e89dce5c1d31cf2772ba/app.go#L55

We just create "a" object (line 42-52) without setting ErrorMiddleware.
So if statement is useless to my POV.

As said in blog.gobuffalo.io ([here](https://blog.gobuffalo.io/buffalo-v0-13-0-released-eac17c4cc4fa) section New Error Handling Middleware), it would be useful to take complete control over all of the error handling. But in fact, it's not that is currently implemented.
Method based on ErrorHandlers may be a good solution to override only 1 or 2 specific error but it would be good to also allow to override error middleware.

If you're agree with that, let me know if you want that I submit a pull request.

**Comment by markbates** [comment] 2019-02-03 22:39
Fixed with #1564 (`v0.14.0-rc.1` - coming this week)

**Closed by markbates** 2019-02-03 22:39 UTC
Labels: breaking change, bug, help wanted

**Comment by sebd71** [comment] 2019-02-07 11:02
Your changes introduce following problems / dangerous behaviors : 

1/  you can create deadlock (forever loop)  
```
app.ErrorHandlers.Default(nil)  // Get will return nil producing forever loop
```

2/ you can reset default handler unintentionally depending on the code order  :
```
app.ErrorHandlers.Default(myDefaultErrorHandler)  // no effect, reset by next lines
app.ErrorHandlers = buffalo.ErrorHandlers{
    404: myErrorHandler,
    500: myErrorHandler,
}
app.ErrorHandlers.Default(myDefaultErrorHandler)  // works fine
```

So make ErrorHandler private seems to me safest and expose (like you did in middleware) Get / Set functions to manage ErrorHandlers.
Please review the pull request I just push
https://github.com/gobuffalo/buffalo/pull/1578

**Comment by markbates** [comment] 2019-02-07 12:13
Thanks for the feedback. I’m not convinced this needs the full rewrite you propose. The first issue can be fixed with a simple nil check. The second one is expected behavior. If I replace the whole ErrorHandlers with a new one, I would expect it to replace any previous changes I made to it. 

I need more convincing that the changes you propose are the right ones.

**Comment by markbates** [comment] 2019-02-07 12:16
I should also point out that you’re requesting breaking changes. I would recommend you open a proposal ticket and lay out your ideas there so the community can discuss the pros/cons of these changes.
