### ISSUE TITLE
when model name is menu got error  could not call menusPath function: missing parameters for /menus/{menus_id}/

### ISSUE THREAD

**Issue by nyrf** [gobuffalo/buffalo#1742] opened 2019-07-18 01:51 UTC
## Description
```
❯ buffalo version
INFO[0001] Buffalo version is: v0.14.6
```
When model name is menu, got error 

```
menus/new.html: line 5: could not call menusPath function: missing parameters for /menus/{menus_id}/: mux: missing route variable "menus_id"
```
### Steps to Reproduce the Problem
  1.  `buffalo new demo --db-type=sqlite3 --skip-webpack --skip-yarn`
  2.  `buffalo g resource menu name link`
  3.  `soda migrate`
  4. visit `http://localhost:3000/menus/new`

then got error

```
ERRO[2019-07-18T09:45:35+08:00] menus/new.html: line 5: could not call menusPath function: missing parameters for /menus/{menus_id}/: mux: missing route variable "menus_id" content_type=text/html db=0s duration=1.936856ms human_size="0 B" method=GET params="{}" path=/menus/new/ render=1.043975ms request_id=pcFdMhOJMZ-zCsKKCOBMz size=0 status=0
```

**Comment by markbates** [comment] 2019-08-15 17:29
Confirmed.

**Comment by paganotoni** [comment] 2020-04-26 16:15
Tried this one on v0.16.8 and could not reproduce it. Can someone retry this one?

**Comment by paganotoni** [comment] 2020-04-26 16:15
cc @stanislas-m

**Comment by paganotoni** [comment] 2020-07-29 17:46
Confirmed this one works with buffalo v0.16.3. Closing it. If issue still happening please reopen.

**Closed by paganotoni** 2020-07-29 17:46 UTC
Labels: bug, help wanted, status-confirmed, status-waiting-for-reply
