### ISSUE TITLE
Creating a new project fails at goimports with Buffalo 0.9.3 and Go 1.9

### ISSUE THREAD

**Issue by siegesmund** [gobuffalo/buffalo#612] opened 2017-08-30 12:45 UTC
Creating a new project fails at goimports. I've read and tried the steps outlined in the Buffalo Troubleshooting FAQ.

Installing with Buffalo 0.9.3 and Go 1.9, I get the following output:

```
--> goimports -w test/actions/actions_test.go test/actions/app.go test/actions/home.go test/actions/home_test.go test/actions/render.go test/grifts/db.go test/grifts/init.go test/main.go test/models/models.go test/models/models_test.go
Usage:
  buffalo new [name] [flags]

Flags:
      --api                  skip all front-end code and configure for an API server
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci] (default "none")
      --db-type string       specify the type of database you want to use [postgres, mysql, sqlite3] (default "postgres")
      --docker string        specify the type of Docker file to generate [none, multi, standard] (default "multi")
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
      --skip-yarn            skip to use npm as the asset package manager
  -v, --verbose              verbosely print out the go get/install commands
      --with-dep             adds github.com/golang/dep to your app

Error: exit status 1
```

**Comment by markbates** [comment] 2017-08-30 12:49
Can you please copy the full output of the `new` command, the cmd string you ran, as well as the output of `buffalo info`? Thanks.

**Comment by siegesmund** [comment] 2017-08-30 12:55
**Command string:**
`buffalo new buffalotest`

**Output:**
```Buffalo version v0.9.3

--> go get -u golang.org/x/tools/cmd/goimports
--> go install golang.org/x/tools/cmd/goimports
--> go get -u github.com/golang/dep/cmd/dep
--> go install github.com/golang/dep/cmd/dep
--> go get -u github.com/motemen/gore
--> go install github.com/motemen/gore
--> /Users/peter/Documents/programming/go/src/buffalotest/README.md
--> /Users/peter/Documents/programming/go/src/buffalotest/actions/actions_test.go
--> /Users/peter/Documents/programming/go/src/buffalotest/actions/app.go
--> /Users/peter/Documents/programming/go/src/buffalotest/actions/home.go
--> /Users/peter/Documents/programming/go/src/buffalotest/actions/home_test.go
--> /Users/peter/Documents/programming/go/src/buffalotest/actions/render.go
--> /Users/peter/Documents/programming/go/src/buffalotest/.codeclimate.yml
--> /Users/peter/Documents/programming/go/src/buffalotest/.gitignore
--> /Users/peter/Documents/programming/go/src/buffalotest/grifts/init.go
--> /Users/peter/Documents/programming/go/src/buffalotest/locales/all.en-us.yaml
--> /Users/peter/Documents/programming/go/src/buffalotest/main.go
--> /Users/peter/Documents/programming/go/src/buffalotest/templates/_flash.html
--> /Users/peter/Documents/programming/go/src/buffalotest/templates/application.html
--> /Users/peter/Documents/programming/go/src/buffalotest/templates/index.html
--> /Users/peter/Documents/programming/go/src/buffalotest/.buffalo.dev.yml
--> goimports -w /Users/peter/Documents/programming/go/src/buffalotest/actions/actions_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/app.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/render.go /Users/peter/Documents/programming/go/src/buffalotest/grifts/init.go /Users/peter/Documents/programming/go/src/buffalotest/main.go
--> /Users/peter/Documents/programming/go/src/buffalotest/assets/images/logo.svg
--> /Users/peter/Documents/programming/go/src/buffalotest/assets/css/application.scss
--> /Users/peter/Documents/programming/go/src/buffalotest/assets/js/application.js
--> /Users/peter/Documents/programming/go/src/buffalotest/.babelrc
--> /Users/peter/Documents/programming/go/src/buffalotest/public/assets/.gitignore
--> /Users/peter/Documents/programming/go/src/buffalotest/webpack.config.js
--> yarn init --no-progress -y
yarn init v0.27.5
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
success Saved package.json
Done in 0.03s.
--> yarn add webpack@~2.3.0 sass-loader@~6.0.5 css-loader@~0.28.4 expose-loader@~0.7.3 style-loader@~0.18.2 node-sass@~4.5.3 extract-text-webpack-plugin@2.1.2 babel-cli@~6.24.1 babel-core@~6.25.0 babel-preset-env@~1.5.2 babel-loader@~7.0.0 url-loader@~0.5.9 file-loader@~0.11.2 jquery@~3.2.1 bootstrap@~3.3.7 path@~0.12.7 font-awesome@~4.7.0 npm-install-webpack-plugin@4.0.4 jquery-ujs@~1.2.2 copy-webpack-plugin@~4.0.1 uglifyjs-webpack-plugin@~0.4.6
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 522 new dependencies.
├─ abbrev@1.1.0
├─ acorn-dynamic-import@2.0.2
├─ acorn@4.0.13
├─ ajv-keywords@1.5.1
├─ ajv@4.11.8
├─ align-text@0.1.4
├─ alphanum-sort@1.0.2
├─ amdefine@1.0.1
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ anymatch@1.3.2
├─ aproba@1.1.2
├─ are-we-there-yet@1.1.4
├─ argparse@1.0.9
├─ arr-diff@2.0.0
├─ arr-flatten@1.1.0
├─ array-find-index@1.0.2
├─ array-unique@0.2.1
├─ asn1.js@4.9.1
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ assert@1.4.1
├─ async-each@1.0.1
├─ async-foreach@0.1.3
├─ async@2.5.0
├─ asynckit@0.4.0
├─ autoprefixer@6.7.7
├─ aws-sign2@0.6.0
├─ aws4@1.6.0
├─ babel-cli@6.24.1
├─ babel-code-frame@6.26.0
├─ babel-core@6.25.0
├─ babel-generator@6.26.0
├─ babel-helper-builder-binary-assignment-operator-visitor@6.24.1
├─ babel-helper-call-delegate@6.24.1
├─ babel-helper-define-map@6.26.0
├─ babel-helper-explode-assignable-expression@6.24.1
├─ babel-helper-function-name@6.24.1
├─ babel-helper-get-function-arity@6.24.1
├─ babel-helper-hoist-variables@6.24.1
├─ babel-helper-optimise-call-expression@6.24.1
├─ babel-helper-regex@6.26.0
├─ babel-helper-remap-async-to-generator@6.24.1
├─ babel-helper-replace-supers@6.24.1
├─ babel-helpers@6.24.1
├─ babel-loader@7.0.0
├─ babel-messages@6.23.0
├─ babel-plugin-check-es2015-constants@6.22.0
├─ babel-plugin-syntax-async-functions@6.13.0
├─ babel-plugin-syntax-exponentiation-operator@6.13.0
├─ babel-plugin-syntax-trailing-function-commas@6.22.0
├─ babel-plugin-transform-async-to-generator@6.24.1
├─ babel-plugin-transform-es2015-arrow-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoped-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoping@6.26.0
├─ babel-plugin-transform-es2015-classes@6.24.1
├─ babel-plugin-transform-es2015-computed-properties@6.24.1
├─ babel-plugin-transform-es2015-destructuring@6.23.0
├─ babel-plugin-transform-es2015-duplicate-keys@6.24.1
├─ babel-plugin-transform-es2015-for-of@6.23.0
├─ babel-plugin-transform-es2015-function-name@6.24.1
├─ babel-plugin-transform-es2015-literals@6.22.0
├─ babel-plugin-transform-es2015-modules-amd@6.24.1
├─ babel-plugin-transform-es2015-modules-commonjs@6.26.0
├─ babel-plugin-transform-es2015-modules-systemjs@6.24.1
├─ babel-plugin-transform-es2015-modules-umd@6.24.1
├─ babel-plugin-transform-es2015-object-super@6.24.1
├─ babel-plugin-transform-es2015-parameters@6.24.1
├─ babel-plugin-transform-es2015-shorthand-properties@6.24.1
├─ babel-plugin-transform-es2015-spread@6.22.0
├─ babel-plugin-transform-es2015-sticky-regex@6.24.1
├─ babel-plugin-transform-es2015-template-literals@6.22.0
├─ babel-plugin-transform-es2015-typeof-symbol@6.23.0
├─ babel-plugin-transform-es2015-unicode-regex@6.24.1
├─ babel-plugin-transform-exponentiation-operator@6.24.1
├─ babel-plugin-transform-regenerator@6.26.0
├─ babel-plugin-transform-strict-mode@6.24.1
├─ babel-polyfill@6.26.0
├─ babel-preset-env@1.5.2
├─ babel-register@6.26.0
├─ babel-runtime@6.26.0
├─ babel-template@6.26.0
├─ babel-traverse@6.26.0
├─ babel-types@6.26.0
├─ babylon@6.18.0
├─ balanced-match@0.4.2
├─ base64-js@1.2.1
├─ bcrypt-pbkdf@1.0.1
├─ big.js@3.1.3
├─ binary-extensions@1.10.0
├─ block-stream@0.0.9
├─ bluebird@2.11.0
├─ bn.js@4.11.8
├─ boom@2.10.1
├─ bootstrap@3.3.7
├─ brace-expansion@1.1.8
├─ braces@1.8.5
├─ brorand@1.1.0
├─ browserify-aes@1.0.6
├─ browserify-cipher@1.0.0
├─ browserify-des@1.0.0
├─ browserify-rsa@4.0.1
├─ browserify-sign@4.0.4
├─ browserify-zlib@0.1.4
├─ browserslist@1.7.7
├─ buffer-xor@1.0.3
├─ buffer@4.9.1
├─ builtin-modules@1.1.1
├─ builtin-status-codes@3.0.0
├─ camelcase-keys@2.1.0
├─ camelcase@3.0.0
├─ caniuse-api@1.6.1
├─ caniuse-db@1.0.30000721
├─ caniuse-lite@1.0.30000721
├─ caseless@0.12.0
├─ center-align@0.1.3
├─ chalk@1.1.3
├─ chokidar@1.7.0
├─ cipher-base@1.0.4
├─ clap@1.2.0
├─ cliui@3.2.0
├─ clone-deep@0.3.0
├─ clone@1.0.2
├─ co@4.6.0
├─ coa@1.0.4
├─ code-point-at@1.1.0
├─ color-convert@1.9.0
├─ color-name@1.1.3
├─ color-string@0.3.0
├─ color@0.11.4
├─ colormin@1.1.2
├─ colors@1.1.2
├─ combined-stream@1.0.5
├─ commander@2.11.0
├─ commondir@1.0.1
├─ concat-map@0.0.1
├─ console-browserify@1.1.0
├─ console-control-strings@1.1.0
├─ constants-browserify@1.0.0
├─ convert-source-map@1.5.0
├─ copy-webpack-plugin@4.0.1
├─ core-js@2.5.0
├─ core-util-is@1.0.2
├─ create-ecdh@4.0.0
├─ create-hash@1.1.3
├─ create-hmac@1.1.6
├─ cross-spawn@3.0.1
├─ cryptiles@2.0.5
├─ crypto-browserify@3.11.1
├─ css-color-names@0.0.4
├─ css-loader@0.28.5
├─ css-selector-tokenizer@0.7.0
├─ cssesc@0.1.0
├─ cssnano@3.10.0
├─ csso@2.3.2
├─ currently-unhandled@0.4.1
├─ dashdash@1.14.1
├─ date-now@0.1.4
├─ debug@2.6.8
├─ decamelize@1.2.0
├─ deep-extend@0.4.2
├─ defined@1.0.0
├─ delayed-stream@1.0.0
├─ delegates@1.0.0
├─ des.js@1.0.0
├─ detect-indent@4.0.0
├─ diffie-hellman@5.0.2
├─ domain-browser@1.1.7
├─ ecc-jsbn@0.1.1
├─ electron-to-chromium@1.3.18
├─ elliptic@6.4.0
├─ emojis-list@2.1.0
├─ enhanced-resolve@3.4.1
├─ errno@0.1.4
├─ error-ex@1.3.1
├─ escape-string-regexp@1.0.5
├─ esprima@2.7.3
├─ esutils@2.0.2
├─ events@1.1.1
├─ evp_bytestokey@1.0.2
├─ expand-brackets@0.1.5
├─ expand-range@1.8.2
├─ expose-loader@0.7.3
├─ extend@3.0.1
├─ extglob@0.3.2
├─ extract-text-webpack-plugin@2.1.2
├─ extsprintf@1.3.0
├─ fast-deep-equal@1.0.0
├─ fastparse@1.1.1
├─ file-loader@0.11.2
├─ filename-regex@2.0.1
├─ fill-range@2.2.3
├─ find-cache-dir@0.1.1
├─ find-up@1.1.2
├─ flatten@1.0.2
├─ font-awesome@4.7.0
├─ for-in@1.0.2
├─ for-own@1.0.0
├─ forever-agent@0.6.1
├─ form-data@2.1.4
├─ fs-extra@0.26.7
├─ fs-readdir-recursive@1.0.0
├─ fs.realpath@1.0.0
├─ fsevents@1.1.2
├─ fstream-ignore@1.0.5
├─ fstream@1.0.11
├─ function-bind@1.1.1
├─ gauge@2.7.4
├─ gaze@1.1.2
├─ get-caller-file@1.0.2
├─ get-stdin@4.0.1
├─ getpass@0.1.7
├─ glob-base@0.3.0
├─ glob-parent@2.0.0
├─ glob@7.1.2
├─ globals@9.18.0
├─ globule@1.2.0
├─ graceful-fs@4.1.11
├─ har-schema@1.0.5
├─ har-validator@4.2.1
├─ has-ansi@2.0.0
├─ has-flag@1.0.0
├─ has-unicode@2.0.1
├─ has@1.0.1
├─ hash-base@2.0.2
├─ hash.js@1.1.3
├─ hawk@3.1.3
├─ hmac-drbg@1.0.1
├─ hoek@2.16.3
├─ home-or-tmp@2.0.0
├─ hosted-git-info@2.5.0
├─ html-comment-regex@1.1.1
├─ http-signature@1.1.1
├─ https-browserify@0.0.1
├─ icss-replace-symbols@1.1.0
├─ icss-utils@2.1.0
├─ ieee754@1.1.8
├─ in-publish@2.0.0
├─ indent-string@2.1.0
├─ indexes-of@1.0.1
├─ indexof@0.0.1
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ ini@1.3.4
├─ interpret@1.0.3
├─ invariant@2.2.2
├─ invert-kv@1.0.0
├─ is-absolute-url@2.1.0
├─ is-arrayish@0.2.1
├─ is-binary-path@1.0.1
├─ is-buffer@1.1.5
├─ is-builtin-module@1.0.0
├─ is-dotfile@1.0.3
├─ is-equal-shallow@0.1.3
├─ is-extendable@0.1.1
├─ is-extglob@1.0.0
├─ is-finite@1.0.2
├─ is-fullwidth-code-point@1.0.0
├─ is-glob@2.0.1
├─ is-number@2.1.0
├─ is-plain-obj@1.1.0
├─ is-plain-object@2.0.4
├─ is-posix-bracket@0.1.1
├─ is-primitive@2.0.0
├─ is-svg@2.1.0
├─ is-typedarray@1.0.0
├─ is-utf8@0.2.1
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ isobject@3.0.1
├─ isstream@0.1.2
├─ jquery-ujs@1.2.2
├─ jquery@3.2.1
├─ js-base64@2.1.9
├─ js-tokens@3.0.2
├─ js-yaml@3.7.0
├─ jsbn@0.1.1
├─ jsesc@1.3.0
├─ json-loader@0.5.7
├─ json-schema-traverse@0.3.1
├─ json-schema@0.2.3
├─ json-stable-stringify@1.0.1
├─ json-stringify-safe@5.0.1
├─ json5@0.5.1
├─ jsonfile@2.4.0
├─ jsonify@0.0.0
├─ jsprim@1.4.1
├─ kind-of@3.2.2
├─ klaw@1.3.1
├─ lazy-cache@0.2.7
├─ lcid@1.0.0
├─ load-json-file@1.1.0
├─ loader-runner@2.3.0
├─ loader-utils@1.1.0
├─ lodash.assign@4.2.0
├─ lodash.camelcase@4.3.0
├─ lodash.clonedeep@4.5.0
├─ lodash.memoize@4.1.2
├─ lodash.mergewith@4.6.0
├─ lodash.tail@4.1.1
├─ lodash.uniq@4.5.0
├─ lodash@4.17.4
├─ longest@1.0.1
├─ loose-envify@1.3.1
├─ loud-rejection@1.6.0
├─ lru-cache@4.1.1
├─ macaddress@0.2.8
├─ map-obj@1.0.1
├─ math-expression-evaluator@1.2.17
├─ md5.js@1.3.4
├─ memory-fs@0.4.1
├─ meow@3.7.0
├─ micromatch@2.3.11
├─ miller-rabin@4.0.0
├─ mime-db@1.29.0
├─ mime-types@2.1.16
├─ mime@1.3.6
├─ minimalistic-assert@1.0.0
├─ minimalistic-crypto-utils@1.0.1
├─ minimatch@3.0.4
├─ minimist@1.2.0
├─ mixin-object@2.0.1
├─ mkdirp@0.5.1
├─ ms@2.0.0
├─ nan@2.7.0
├─ node-dir@0.1.17
├─ node-gyp@3.6.2
├─ node-libs-browser@2.0.0
├─ node-pre-gyp@0.6.36
├─ node-sass@4.5.3
├─ nopt@3.0.6
├─ normalize-package-data@2.4.0
├─ normalize-path@2.1.1
├─ normalize-range@0.1.2
├─ normalize-url@1.9.1
├─ npm-install-webpack-plugin@4.0.4
├─ npmlog@4.1.2
├─ num2fraction@1.2.2
├─ number-is-nan@1.0.1
├─ oauth-sign@0.8.2
├─ object-assign@4.1.1
├─ object.omit@2.0.1
├─ once@1.4.0
├─ os-browserify@0.2.1
├─ os-homedir@1.0.2
├─ os-locale@1.4.0
├─ os-tmpdir@1.0.2
├─ osenv@0.1.4
├─ output-file-sync@1.1.2
├─ pako@0.2.9
├─ parse-asn1@5.1.0
├─ parse-glob@3.0.4
├─ parse-json@2.2.0
├─ path-browserify@0.0.0
├─ path-exists@2.1.0
├─ path-is-absolute@1.0.1
├─ path-type@1.1.0
├─ path@0.12.7
├─ pbkdf2@3.0.13
├─ performance-now@0.2.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ pkg-dir@1.0.0
├─ postcss-calc@5.3.1
├─ postcss-colormin@2.2.2
├─ postcss-convert-values@2.6.1
├─ postcss-discard-comments@2.0.4
├─ postcss-discard-duplicates@2.1.0
├─ postcss-discard-empty@2.1.0
├─ postcss-discard-overridden@0.1.1
├─ postcss-discard-unused@2.2.3
├─ postcss-filter-plugins@2.0.2
├─ postcss-merge-idents@2.1.7
├─ postcss-merge-longhand@2.0.2
├─ postcss-merge-rules@2.1.2
├─ postcss-message-helpers@2.0.0
├─ postcss-minify-font-values@1.0.5
├─ postcss-minify-gradients@1.0.5
├─ postcss-minify-params@1.2.2
├─ postcss-minify-selectors@2.1.1
├─ postcss-modules-extract-imports@1.2.0
├─ postcss-modules-local-by-default@1.2.0
├─ postcss-modules-scope@1.1.0
├─ postcss-modules-values@1.3.0
├─ postcss-normalize-charset@1.1.1
├─ postcss-normalize-url@3.0.8
├─ postcss-ordered-values@2.2.3
├─ postcss-reduce-idents@2.4.0
├─ postcss-reduce-initial@1.0.1
├─ postcss-reduce-transforms@1.0.4
├─ postcss-selector-parser@2.2.3
├─ postcss-svgo@2.1.6
├─ postcss-unique-selectors@2.0.2
├─ postcss-value-parser@3.3.0
├─ postcss-zindex@2.2.0
├─ postcss@5.2.17
├─ prepend-http@1.0.4
├─ preserve@0.2.0
├─ private@0.1.7
├─ process-nextick-args@1.0.7
├─ process@0.11.10
├─ prr@0.0.0
├─ pseudomap@1.0.2
├─ public-encrypt@4.0.0
├─ punycode@1.4.1
├─ q@1.5.0
├─ qs@6.4.0
├─ query-string@4.3.4
├─ querystring-es3@0.2.1
├─ querystring@0.2.0
├─ randomatic@1.1.7
├─ randombytes@2.0.5
├─ rc@1.2.1
├─ read-pkg-up@1.0.1
├─ read-pkg@1.1.0
├─ readable-stream@2.3.3
├─ readdirp@2.1.0
├─ redent@1.0.0
├─ reduce-css-calc@1.3.0
├─ reduce-function-call@1.0.2
├─ regenerate@1.3.2
├─ regenerator-runtime@0.10.5
├─ regenerator-transform@0.10.1
├─ regex-cache@0.4.3
├─ regexpu-core@1.0.0
├─ regjsgen@0.2.0
├─ regjsparser@0.1.5
├─ remove-trailing-separator@1.1.0
├─ repeat-element@1.1.2
├─ repeat-string@1.6.1
├─ repeating@2.0.1
├─ request@2.81.0
├─ require-directory@2.1.1
├─ require-main-filename@1.0.1
├─ right-align@0.1.3
├─ rimraf@2.6.1
├─ ripemd160@2.0.1
├─ safe-buffer@5.1.1
├─ sass-graph@2.2.4
├─ sass-loader@6.0.6
├─ sax@1.2.4
├─ schema-utils@0.3.0
├─ scss-tokenizer@0.2.3
├─ semver@5.4.1
├─ set-blocking@2.0.0
├─ set-immediate-shim@1.0.1
├─ setimmediate@1.0.5
├─ sha.js@2.4.8
├─ shallow-clone@0.1.2
├─ signal-exit@3.0.2
├─ slash@1.0.0
├─ sntp@1.0.9
├─ sort-keys@1.1.2
├─ source-list-map@2.0.0
├─ source-map-support@0.4.16
├─ source-map@0.5.7
├─ spdx-correct@1.0.2
├─ spdx-expression-parse@1.0.4
├─ spdx-license-ids@1.2.2
├─ sprintf-js@1.0.3
├─ sshpk@1.13.1
├─ stdout-stream@1.4.0
├─ stream-browserify@2.0.1
├─ stream-http@2.7.2
├─ strict-uri-encode@1.1.0
├─ string_decoder@0.10.31
├─ string-width@1.0.2
├─ stringstream@0.0.5
├─ strip-ansi@3.0.1
├─ strip-bom@2.0.0
├─ strip-indent@1.0.1
├─ strip-json-comments@2.0.1
├─ style-loader@0.18.2
├─ supports-color@3.2.3
├─ svgo@0.7.2
├─ tapable@0.2.8
├─ tar-pack@3.4.0
├─ tar@2.2.1
├─ timers-browserify@2.0.4
├─ to-arraybuffer@1.0.1
├─ to-fast-properties@1.0.3
├─ tough-cookie@2.3.2
├─ trim-newlines@1.0.0
├─ trim-right@1.0.1
├─ tty-browserify@0.0.0
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ uglify-js@2.8.29
├─ uglify-to-browserify@1.0.2
├─ uglifyjs-webpack-plugin@0.4.6
├─ uid-number@0.0.6
├─ uniq@1.0.1
├─ uniqid@4.1.1
├─ uniqs@2.0.0
├─ url-loader@0.5.9
├─ url@0.11.0
├─ user-home@1.1.1
├─ util-deprecate@1.0.2
├─ util@0.10.3
├─ uuid@3.1.0
├─ v8flags@2.1.1
├─ validate-npm-package-license@3.0.1
├─ vendors@1.0.1
├─ verror@1.10.0
├─ vm-browserify@0.0.4
├─ watchpack@1.4.0
├─ webpack-sources@1.0.1
├─ webpack@2.3.3
├─ whet.extend@0.9.9
├─ which-module@1.0.0
├─ which@1.3.0
├─ wide-align@1.1.2
├─ window-size@0.1.0
├─ wordwrap@0.0.2
├─ wrap-ansi@2.1.0
├─ wrappy@1.0.2
├─ xtend@4.0.1
├─ y18n@3.2.1
├─ yallist@2.1.2
├─ yargs-parser@4.2.1
└─ yargs@6.6.0
Done in 11.36s.
--> goimports -w /Users/peter/Documents/programming/go/src/buffalotest/actions/actions_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/app.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/render.go /Users/peter/Documents/programming/go/src/buffalotest/grifts/init.go /Users/peter/Documents/programming/go/src/buffalotest/main.go
--> /Users/peter/Documents/programming/go/src/buffalotest/models/models.go
--> /Users/peter/Documents/programming/go/src/buffalotest/models/models_test.go
--> /Users/peter/Documents/programming/go/src/buffalotest/grifts/db.go
--> go get github.com/markbates/pop/...
--> go install github.com/markbates/pop/soda
--> database.yml
--> goimports -w actions/actions_test.go actions/app.go actions/home.go actions/home_test.go actions/render.go grifts/db.go grifts/init.go main.go models/models.go models/models_test.go
--> goimports -w /Users/peter/Documents/programming/go/src/buffalotest/actions/actions_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/app.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/render.go /Users/peter/Documents/programming/go/src/buffalotest/grifts/db.go /Users/peter/Documents/programming/go/src/buffalotest/grifts/init.go /Users/peter/Documents/programming/go/src/buffalotest/main.go /Users/peter/Documents/programming/go/src/buffalotest/models/models.go /Users/peter/Documents/programming/go/src/buffalotest/models/models_test.go
--> /Users/peter/Documents/programming/go/src/buffalotest/Dockerfile
--> /Users/peter/Documents/programming/go/src/buffalotest/.dockerignore
--> goimports -w /Users/peter/Documents/programming/go/src/buffalotest/actions/actions_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/app.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/render.go /Users/peter/Documents/programming/go/src/buffalotest/grifts/db.go /Users/peter/Documents/programming/go/src/buffalotest/grifts/init.go /Users/peter/Documents/programming/go/src/buffalotest/main.go /Users/peter/Documents/programming/go/src/buffalotest/models/models.go /Users/peter/Documents/programming/go/src/buffalotest/models/models_test.go
--> goimports -w /Users/peter/Documents/programming/go/src/buffalotest/actions/actions_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/app.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home.go /Users/peter/Documents/programming/go/src/buffalotest/actions/home_test.go /Users/peter/Documents/programming/go/src/buffalotest/actions/render.go /Users/peter/Documents/programming/go/src/buffalotest/grifts/db.go /Users/peter/Documents/programming/go/src/buffalotest/grifts/init.go /Users/peter/Documents/programming/go/src/buffalotest/main.go /Users/peter/Documents/programming/go/src/buffalotest/models/models.go /Users/peter/Documents/programming/go/src/buffalotest/models/models_test.go
--> go get -t ./...
package /Users/peter/Documents/programming/go/buffalotest/actions: unrecognized import path "/Users/peter/Documents/programming/go/buffalotest/actions" (import path does not begin with hostname)
package /Users/peter/Documents/programming/go/buffalotest/models: unrecognized import path "/Users/peter/Documents/programming/go/buffalotest/models" (import path does not begin with hostname)
--> goimports -w buffalotest/actions/actions_test.go buffalotest/actions/app.go buffalotest/actions/home.go buffalotest/actions/home_test.go buffalotest/actions/render.go buffalotest/grifts/db.go buffalotest/grifts/init.go buffalotest/main.go buffalotest/models/models.go buffalotest/models/models_test.go
Usage:
  buffalo new [name] [flags]

Flags:
      --api                  skip all front-end code and configure for an API server
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci] (default "none")
      --db-type string       specify the type of database you want to use [postgres, mysql, sqlite3] (default "postgres")
      --docker string        specify the type of Docker file to generate [none, multi, standard] (default "multi")
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
      --skip-yarn            skip to use npm as the asset package manager
  -v, --verbose              verbosely print out the go get/install commands
      --with-dep             adds github.com/golang/dep to your app

Error: exit status 1```

**Buffalo info output:**
Buffalo version v0.9.3

### Buffalo Version
v0.9.3

### Go Version
go version go1.9 darwin/amd64

### Go Env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/peter/Documents/Programming/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8j/x1j8540j06v36_hs27sck0sw0000gn/T/go-build675644878=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### Node Version
v6.10.1

### NPM Version
3.10.10

### Dep Status
could not find project Gopkg.toml, use dep init to initiate a manifest

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
3.16.0 2016-11-04 19:09:39 0e5ffd9123d6d2d2b8f3701e8a73cc98a3a7ff5f

**Comment by markbates** [comment] 2017-08-30 14:28
I'm unable to reproduce, but looking at this error `package /Users/peter/Documents/programming/go/buffalotest/models: unrecognized import path "/Users/peter/Documents/programming/go/buffalotest/models" (import path does not begin with hostname)` it looks like `goimports` doesn't like something about your path.

With that said, it looks like you're `$GOPATH` has capitals in it: 

```
GOPATH="/Users/peter/Documents/Programming/Go"
``` 

but your path doesn't:

```
/Users/peter/Documents/programming/go/src
```

Perhaps the problem is these things don't match.

**Comment by markbates** [comment] 2017-08-30 14:30
I can reproduce if I set my `GOPATH` to have capitals that don't match my file system. Fix your `GOPATH` and you should be good to Go. :) (yes, pun completely intended.)

**Comment by markbates** [comment] 2017-08-30 14:47
I added a new Troubleshooting section for this. https://gobuffalo.io/docs/troubleshooting Thanks for finding it. Hopefully correcting your `$GOPATH` will solve the problem for you. I'm closing for now. Please re-open if the problem persists.

**Closed by markbates** 2017-08-30 14:47 UTC

**Comment by siegesmund** [comment] 2017-08-30 19:48
Thanks for the assist. Really basic problem; I just didn't see it because it rarely bites me.
