### ISSUE TITLE
Buffalo - Heroku Buildpack

### ISSUE THREAD

**Issue by bscott** [gobuffalo/buffalo#159] opened 2017-01-22 06:42 UTC
Creating this issue just as a reminder to test the Heroku Go buildpack with Buffalo.

**Comment by apaganobeleno** [comment] 2017-01-22 16:48
@bscott this one depends on #134 (given heroku buildpack supports Glide) and adding  a `Procfile` to the generated app, should we create an issue to add the `Procfile` to the `new` generated app ?

**Comment by bscott** [comment] 2017-01-23 01:53
@apaganobeleno I think we should but your right as Heroku does only support Godeps atm.

**Comment by apaganobeleno** [comment] 2017-01-23 01:57
@bscott I think it supports Glide as well, yes, just confirmed:

https://github.com/heroku/heroku-buildpack-go/blob/master/README.md

**Comment by bscott** [comment] 2017-01-23 01:59
@apaganobeleno Nice

**Comment by philipithomas** [comment] 2017-01-27 22:41
It would be nice to document how to run grift commands as cron jobs on heroku too

**Comment by apaganobeleno** [comment] 2017-02-22 14:21
@bscott @markbates i can spend some time working on this one (i need it), do you guys think its pertinent to work on this one now ?

**Comment by markbates** [comment] 2017-02-22 14:23
@apaganobeleno if you need it, then it's pertinent. :)

**Comment by apaganobeleno** [comment] 2017-02-22 14:24
@markbates awesome, i'll keep you posted on this one, thanks!

**Comment by apaganobeleno** [comment] 2017-02-23 01:06
@markbates @bscott i built a [very basic buildpack](https://github.com/apaganobeleno/heroku-buildpack-buffalo) for buffalo, it compiles the app successfully but at the end i'm having the same issue i've mentioned over slack.

When running the app it says:

```
panic: could not locate box "../public/assets"
```

Any idea what could i be missing ?

**Comment by apaganobeleno** [comment] 2017-02-23 01:19
This is the app i'm using with the buildpack -> https://github.com/apaganobeleno/app

**Comment by freeformz** [comment] 2017-02-23 02:18
I am the maintainer of the heroku go buildpack, so If you have any needs that aren't met by it, then I am interested in fixing it in the buildpack. I have considered directly adding support for buffalo in the buildpack, but it hasn't reached the top of my queue yet.

**Comment by apaganobeleno** [comment] 2017-02-23 13:37
hey @freeformz, thanks for reaching out, and thanks for the heroku-go build-pack! i've mostly copy/pasted the code from it and heroku-nodejs build-pack.

We're having an issue after building the app where it doesn't find some embedded assets, IDK if its something that i'm doing wrong with the env variables or some dependency that go.rice has and i have not included in the build-pack, i'll continue looking into this but anyways any help you could give us with this is appreciated.

**Comment by markbates** [comment] 2017-02-23 14:44
@apaganobeleno it sounds like the same issue from. Try creating the missing folder in the build pack.

**Comment by markbates** [comment] 2017-02-23 14:46
That folder isn't checked in, it's in the .gitignore because webpack should build it.

**Comment by apaganobeleno** [comment] 2017-02-23 14:55
Yes, right, i just [modified the buildpack to add it](https://github.com/apaganobeleno/heroku-buildpack-buffalo/blob/master/bin/compile#L100) but it still doesn't work :(.

**Comment by freeformz** [comment] 2017-02-23 18:13
Assuming the `git push heroku master` workflow of a gobuffalo project that has a `glide.yaml` (or other vendor tool's file(s)) checked in, what is the most reliable way to determine that the code being received on the other side is a gobuffalo project? I'm thinking of sniffing for `actions/app.go` and looking for an import of `github.com/gobuffalo/buffalo`. Does that sound reasonable?

**Comment by apaganobeleno** [comment] 2017-02-23 20:39
@freeformz i think by checking the existence of the `buffalo.dev.yml` should be enough.

**Comment by freeformz** [comment] 2017-02-24 16:40
@apaganobeleno I can't find that file anywhere in my test gobuffalo project created with v0.7.3.

**Comment by markbates** [comment] 2017-02-24 17:35
It's a hidden dot file '.buffalo.dev.yml'

**Comment by freeformz** [comment] 2017-02-24 17:41
hah. So it is!

**Comment by markbates** [comment] 2017-06-01 15:40
I wonder if we still need this ticket now that we have docker images. https://blog.gobuffalo.io/deploying-buffalo-to-heroku-with-docker-adafa4afdd6f It's so easy to deploy to heroku using the docker images it's not even funny. Thoughts on closing this?

**Comment by apaganobeleno** [comment] 2017-06-01 15:43
@markbates we should close it now that we've provided a concise deployment strategy and steps, this ticket is more about that than using heroku build-packs (which i love).

**Comment by markbates** [comment] 2017-06-01 15:48
Cool. I'm going to close this.

**Closed by markbates** 2017-06-01 15:48 UTC
Labels: Enhancement
