### ISSUE TITLE
actions-packr.go: path error in windows

### ISSUE THREAD

**Issue by lanybass** [gobuffalo/buffalo#347] opened 2017-04-01 06:51 UTC
>package actions
>import "github.com/gobuffalo/packr"
>// GENERATE FILE
>// Do NOT hand edit this file
>// It is recommended that you do not check into this file into SCM.
>// We STRONGLY recommend you delete this file after you have built your
>// Go binary. You can use the "packr clean" command to clean up this,
>// and any other packr generated files.
>func init() {
>	packr.PackJSONBytes("../templates", "D:\Go\GOPATH\src\oschina.net\lanybass\erciyibiao\templates\_flash.html", "\"...\"")
>	packr.PackJSONBytes("../templates", "D:\Go\GOPATH\src\oschina.net\lanybass\erciyibiao\templates\application.html", "\"...\"")
>	packr.PackJSONBytes("../templates", "D:\Go\GOPATH\src\oschina.net\lanybass\erciyibiao\templates\index.html", "\"...\"")
>}

the slashes in D:\ should be replaced with \\ or /

**Comment by as27** [comment] 2017-04-01 10:58
The problem at this point is when generating a filepath into go file `\` needs to be escaped.

For example the generated file should look like this:
```
myPath := "C:\\Go\\src\\myfolder\\myproject"
```

**Comment by markbates** [comment] 2017-04-01 13:34
It shouldn't be generating absolute paths at all. It should be relative paths. If it's generating full paths, that's the problem.

**Comment by as27** [comment] 2017-04-01 14:19
Not only the absolute path. I could reproduce an error.

See line 12:
```
packr.PackJSONBytes("../public/assets", "C:\Users\Schroepfer\go\src\tutorials\tmpltest\public\assets\.gitignore", "\"\"")
```
Which gave following error:
```
# tutorials/tmpltest/actions
actions\actions-packr.go:12: non-hex character in escape sequence: s
actions\actions-packr.go:12: unknown escape sequence
```

**Comment by markbates** [comment] 2017-04-01 14:26
So who amongst you windows developers wants to help me out and fix this? :) pretty please. With sugar on top. 

I don't have a windows box so I would just be hacking around trying to figure it out.

**Comment by as27** [comment] 2017-04-01 15:37
I can try it, but I need some time to understand the package. 
I would try to fix it inside the packr package.
`go test` inside packr fails under windows, but it seems at another point.

**Comment by lanybass** [comment] 2017-04-01 16:26
I have resolved 2 problem,but I think it's not ideal.
1.the slash error:
>file :: src\github.com\gobuffalo\packr\builder\box.go
>func (b *box) Walk(root string) error {
>	return filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
>		if info == nil || info.IsDir() {
>			return nil
>		}
>		path = strings.Replace(path, "\\", "/", -1)  // added by me
>		root = strings.Replace(root, "\\", "/", -1)  // added by me
>		// after added lines above , there has no prefix path and no '\' in the Name
>		f := file{
>			Name: strings.Replace(path, root+"/", "", 1),
>		}

2. generate ***-packr.go failed , since there is a '\r' at the end of *** ,I don't know where it come from, I just removed '\r'
>file :: D:\Go\GOPATH\src\github.com\gobuffalo\packr\builder\builder.go
>func (b *Builder) dump() error {
>	for _, p := range b.pkgs {
>		p.Name = strings.Replace(p.Name, "\r", "", -1) // added by me
>		name := filepath.Join(p.Dir, p.Name+"-packr.go")
>		fmt.Printf("--> packing %s\n", name)

now the exe is builded successful.

but I have another puzzle, I use "buffalo build", all the assets and templates a in the binary file,
why when I execute the exe, it still load template file from my absolute path D:\***\***\ (Proved by opps after renamed a html file )

**Comment by markbates** [comment] 2017-04-01 16:49
If it's loading from the absolute path that means it can't find it in the binary, probably because you have changed the path names in the binary. 

Let's say you are trying to access `foo/index.html` in a box created with the path `../templates`. if you change the path of `foo/index.html` in the binary to something else, like `foo\index.html`, then it won't be able to find it because there is no entry matching that. Hopefully that makes sense. 

It sounds like there is some "normalization" issues we need to fix so that all paths are identical, and yet, should they need to, can be resolved to disk. 

This problem is probably more apparent when building a Linux binary on windows, as the paths are generated with windows paths, which won't work on a Linux binary.

**Comment by as27** [comment] 2017-04-01 17:59
There is a bug inside the packr under windows. I have also the `\r` inside the package name, when running builder_test.go inside packr.

**Comment by markbates** [comment] 2017-04-01 20:13
After setting up virtual box and windows, I think I have a PR that solves this all. At least, it seems to be working in my virtual windows, and on my mac.

I would love it if some actual windows type people could play with it and see if it solves these problems:

Here is the PR:
https://github.com/gobuffalo/packr/pull/2/files

Here is the branch:
https://github.com/gobuffalo/packr/tree/windows

To test it with Buffalo you will need to pull down the packr `windows` branch and the rebuild your local Buffalo binary to pick up the packr changes.

Please let me know if this works so I can merge in that PR and we can all rejoice.

**Comment by lanybass** [comment] 2017-04-02 04:20
if you just test this via a test script , may it not be ok.
didn't you meet '\r' in var 'Name'   of builder/builder.go ?
I'll try it later 
nice sunday, I'm going out

**Comment by lanybass** [comment] 2017-04-02 07:49
I've tried your branch. you didn't deal with the '\r'
`-packr.go: The filename, directory name, or volume label syntax is incorrect.`
@markbates

**Comment by as27** [comment] 2017-04-02 09:31
Now I found why `\r` is just under windows.

Inside a go file windows line ends are `\r\n`. By extracting the package name out of the file the `\r` is part of the name. 
https://github.com/gobuffalo/packr/blob/windows/builder/builder.go#L90

After other systems just have `\n` this does just appear on windows.

**Comment by markbates** [comment] 2017-04-02 15:53
I'm definitely going to need a windows person to fix this. For me all the tests pass and built binaries are working as expected in the windows branch I posted. Maybe it's because I'm using virtual box and not a "real" windows system.  I don't know.

**Comment by lanybass** [comment] 2017-04-02 17:46
@markbates 
maybe your IDE formatted your code in a linux format ,all lines ended with \n not crlf

**Comment by markbates** [comment] 2017-04-02 17:56
I honestly don't know. I'm not a windows dev. What I need is someone who understands the issue and can reproduce it to jump in and make the fix.

**Comment by lanybass** [comment] 2017-04-02 18:02
I changed this line to resolve this:
```go
var packagePattern = regexp.MustCompile(`package\s+([^\r]+)`)
```
chang `\s+(.+)` to `\s+([^\r]+)`
I fixed this .. but the "assets" problem still be there.
even you can build successfully , bu when you build out an exe , is dosn't work without assts dir, you can try it
@markbates

**Comment by lanybass** [comment] 2017-04-02 18:49
you don't need to know something about windows, just help me to find out why the file in box can not be found . tks

![234234](https://cloud.githubusercontent.com/assets/592922/24590046/162b5d70-1818-11e7-9f12-d3982cdc3e67.png)

**Comment by markbates** [comment] 2017-04-02 19:39
@lanybass you only get the assets.zip file if you use the `-e` flag. did you do that?

also, i pushed up another commit to that windows branch, that i think resolves the files not being found. if you could test that would be great.

**Comment by lanybass** [comment] 2017-04-02 20:17
bingo~
I've tested, it's ok now
and it has noting to do with "assets.zip" , you don't need to modify "box.go"
@markbates 
you can merge and close it now

**Comment by lanybass** [comment] 2017-04-02 20:47
I think I found a new issue, about performance::
![2017-04-03 04 30 37](https://cloud.githubusercontent.com/assets/592922/24590883/e4f90058-1827-11e7-9f92-6c9193fe143f.png)
I visit the site and reload agin and agin but the http status code always be `200` but not `304`
I tried to test builtin lib `http.FileServer()`,it has no this bug

**Comment by markbates** [comment] 2017-04-02 20:52
Ok, so this seems to be fixed now with https://github.com/gobuffalo/packr/pull/2. @lanybass can you please open an issue for that performance issue in the packr repo itself? Thanks.

**Closed by markbates** 2017-04-02 20:52 UTC
Labels: windows
