### ISSUE TITLE
Unsuccessful: buffalo new <name> --skip-pop

### ISSUE THREAD

**Issue by andranikmirzoyan** [gobuffalo/buffalo#497] opened 2017-07-07 23:07 UTC
Hi All, 

I'm fairly new to this... been pulling my hair trying to figure out why this is failing... I'd be grateful if anyone can show me some direction.

Some background information:

OS: Ubunto 16.04

Profile:
export GOROOT="/usr/local/go"
export GOPATH="/home/amirzoyan/work"
export GOBIN="$GOPATH/bin"
export PATH="/usr/local/go/bin:$GOBIN:$PATH"

go version:
go version go1.8.3 linux/amd64

Environments:
XDG_SESSION_ID=25
TERM=xterm-256color
SHELL=/bin/bash
SSH_CLIENT=4.7.30.2 36208 22
GOBIN=/home/amirzoyan/work/bin
SSH_TTY=/dev/pts/0
USER=amirzoyan
MAIL=/var/mail/amirzoyan
PATH=/usr/local/go/bin:/home/amirzoyan/work/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/amirzoyan
LANG=en_US.UTF-8
NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
SHLVL=1
HOME=/home/amirzoyan
GOROOT=/usr/local/go
LOGNAME=amirzoyan
GOPATH=/home/amirzoyan/work
XDG_RUNTIME_DIR=/run/user/1000
OLDPWD=/home/amirzoyan
_=/usr/bin/env

buffalo version:
Buffalo version is: v0.9.0

Failing build:
`
buffalo new baldeagle --skip-pop
--> npm install --save webpack@~2.3.0 sass-loader css-loader style-loader node-sass extract-text-webpack-plugin babel-cli babel-core babel-preset-env babel-loader url-loader file-loader jquery bootstrap path font-awesome npm-install-webpack-plugin jquery-ujs copy-webpack-plugin expose-loader
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
> node-sass@4.5.3 install /home/amirzoyan/work/src/github.com/amirzoyan/amirzoyan/node_modules/node-sass
> node scripts/install.js
--> goimports -w actions/actions_test.go actions/app.go actions/home.go actions/home_test.go actions/render.go grifts/routes.go main.go
--> goimports -w amirzoyan/actions/actions_test.go amirzoyan/actions/app.go amirzoyan/actions/home.go amirzoyan/actions/home_test.go amirzoyan/actions/render.go amirzoyan/grifts/routes.go amirzoyan/main.go
Usage:
  buffalo new [name] [flags]
Flags:
      --api                  skip all front-end code and configure for an API server
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci] (default "none")
      --db-type string       specify the type of database you want to use [postgres, mysql, sqlite3] (default "postgres")
      --docker string        specify the type of Docker file to generate [none, multi, standard] (default "multi")
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --skip-dep             skips adding github.com/golang/dep to your app
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
  -v, --verbose              verbosely print out the go get/install commands
      --with-yarn            allows the use of yarn instead of npm as dependency manager
Error: exit status 1
`

**Comment by markbates** [comment] 2017-07-07 23:29
Is there any other output? Does it work if you don't pass the --skip-pop flag?

**Comment by edmwagner** [comment] 2017-07-13 02:36
Trying again today.  If there is a way for more verbose output I'll try it.

today I ran threw new setup following: http://gopherguides.com/before-you-come-to-class
Then http://gobuffalo.io/docs/getting-started

I see the result is the similar but buffalo version is updated and exit status is 2. output follows:


![image](https://user-images.githubusercontent.com/10358884/28148031-548bf582-6752-11e7-88ce-23216c61e017.png)

**Comment by edmwagner** [comment] 2017-07-13 02:38
Will remove created code dir and try without `--skip-pop`.  Should I add `--db-type mysql` ?  otherwise docs indicate sqlite will be used and require gcc which I do not have at this time.

**Comment by markbates** [comment] 2017-07-13 02:49
Unfortunately the docs were wrong and have been amended. Even if you are not using SQLite. Sorry for the confusing.

-----------
Mark Bates

**Comment by edmwagner** [comment] 2017-07-13 02:53
Ahh.  Mark just noticed your comment about missing gcc.    I'll add gcc to cygwin and before and try running from under cygwin sell

**Comment by markbates** [comment] 2017-07-19 00:17
Closing this since it is basically a duplicate of #500

**Closed by markbates** 2017-07-19 00:17 UTC
