### ISSUE TITLE
Docker images cannot be pulled from Docker Hub if the full path to the image is specified

### ISSUE THREAD

**Issue by jbharper86** [gobuffalo/buffalo#2052] opened 2020-09-29 21:06 UTC
### Description

The buffalo images on Docker Hub cannot be pulled if the full image path is specified like so: `registry.hub.docker.com/library/gobuffalo/buffalo:v0.16.15`

If you just specify `gobuffalo/buffalo:v0.16.15` the image can be pulled, but only if `registry.hub.docker.com` is being used as the default registry. However, this is not always the case. For example, when using gitlab CI with the container registry enabled, the default registry will be the container registry for that gitlab instance. The only way around this limitation is to specify the full image path, but this cannot currently be done for buffalo images.

When attempting to pull the buffalo images using the full image path, Docker Hub requires authentication. Normally this wouldn't be an issue. You would just run `docker login registry.hub.docker.com` and repeat the docker pull command. However, even after logging in Docker Hub will still return an authentication error.

### Steps to Reproduce the Problem

  1. `docker pull gobuffalo/buffalo:v0.16.15`
> v0.16.15: Pulling from gobuffalo/buffalo
Digest: sha256:fe762ab1b84ea63dfce16321e1c0ff704d40e5e686c9c8fb12fb3aeaba3be45f
Status: Image is up to date for gobuffalo/buffalo:v0.16.15
docker.io/gobuffalo/buffalo:v0.16.15

  2. `docker pull registry.hub.docker.com/library/gobuffalo/buffalo:v0.16.15`
> Error response from daemon: unauthorized: authentication required

  3. `docker login registry.hub.docker.com`
> Username: *****
Password: *****
Login Succeeded

  4. `docker pull registry.hub.docker.com/library/gobuffalo/buffalo:v0.16.15`
> Error response from daemon: unauthorized: authentication required

### Expected Behavior

The `docker pull registry.hub.docker.com/library/gobuffalo/buffalo:v0.16.15` command should function exactly the same as `docker pull gobuffalo/buffalo:v0.16.15`.

### Actual Behavior

Running `docker pull registry.hub.docker.com/library/gobuffalo/buffalo:v0.16.15` actually results in an authentication error, and even after successfully logging into Docker Hub the image cannot be pulled.

**Comment by paganotoni** [comment] 2020-10-07 18:55
Hey @jbharper86 👋. I was able to reproduce it but don't have much idea of how to solve it, seems to be more related with docker than with Buffalo. Do you have any idea of how to solve it ?

**Comment by Fuuzetsu** [comment] 2021-04-28 07:34
I landed here after Googling about similar issue. You can deal with this by dropping `library` component. So instead of

```console
$ docker pull registry.hub.docker.com/library/gobuffalo/buffalo:v0.16.15
```
you can run
```console
$ docker pull registry.hub.docker.com/gobuffalo/buffalo:v0.16.15
```

I don't know what the exact criteria is here: perhaps the repositories with forward slashes in them go in their own namespace whereas repositories that belong at top-level (such as `ubuntu`) are implicitly put into the `library` namespace?

I managed to figure this out thanks to https://github.com/Azure/acr/issues/476#issuecomment-709544470

**Comment by paganotoni** [comment] 2021-04-28 11:57
thanks @Fuuzetsu

**Closed by paganotoni** 2021-04-28 11:57 UTC
