### ISSUE TITLE
Error creating new <project> on Windows

### ISSUE THREAD

**Issue by muloka** [gobuffalo/buffalo#647] opened 2017-09-19 20:50 UTC
## Go

go version go1.9 windows/amd64

## Buffalo

Buffalo version is: v0.9.4

## Powershell output

```
G:\go\src> buffalo new coke
Buffalo version v0.9.4

--> go get -u golang.org/x/tools/cmd/goimports
--> go get -u github.com/golang/dep/cmd/dep
--> go get -u github.com/motemen/gore
--> G:\go\src\coke\README.md
--> G:\go\src\coke\actions\actions_test.go
--> G:\go\src\coke\actions\app.go
--> G:\go\src\coke\actions\home.go
--> G:\go\src\coke\actions\home_test.go
--> G:\go\src\coke\actions\render.go
--> G:\go\src\coke\.codeclimate.yml
--> G:\go\src\coke\.gitignore
--> G:\go\src\coke\grifts\init.go
--> G:\go\src\coke\locales\all.en-us.yaml
--> G:\go\src\coke\main.go
--> G:\go\src\coke\templates\_flash.html
--> G:\go\src\coke\templates\application.html
--> G:\go\src\coke\templates\index.html
--> G:\go\src\coke\.buffalo.dev.yml
--> goimports -w G:\go\src\coke\actions\actions_test.go G:\go\src\coke\actions\app.go G:\go\src\coke\actions\home.go G:\
go\src\coke\actions\home_test.go G:\go\src\coke\actions\render.go G:\go\src\coke\grifts\init.go G:\go\src\coke\main.go
--> G:\go\src\coke\assets\images\logo.svg
--> G:\go\src\coke\assets\css\application.scss
--> G:\go\src\coke\assets\js\application.js
--> G:\go\src\coke\.babelrc
--> G:\go\src\coke\public\assets\.gitignore
--> G:\go\src\coke\webpack.config.js
--> yarn init --no-progress -y
yarn init v1.0.2
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implicati
ons.
success Saved package.json
Done in 0.03s.
--> yarn add webpack@~2.3.0 sass-loader@~6.0.5 css-loader@~0.28.4 expose-loader@~0.7.3 style-loader@~0.18.2 node-sass@~4
.5.3 extract-text-webpack-plugin@2.1.2 babel-cli@~6.24.1 babel-core@~6.25.0 babel-preset-env@~1.5.2 babel-loader@~7.0.0
url-loader@~0.5.9 file-loader@~0.11.2 jquery@~3.2.1 bootstrap-sass@~3.3.7 path@~0.12.7 font-awesome@~4.7.0 npm-install-w
ebpack-plugin@4.0.4 jquery-ujs@~1.2.2 copy-webpack-plugin@~4.0.1 uglifyjs-webpack-plugin@~0.4.6
yarn add v1.0.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
[4/4] Building fresh packages...
[1/2] ⡀ node-sass
[2/2] ⡀ uglifyjs-webpack-plugin
[-/2] ⡀ waiting...
[-/2] ⡀ waiting...
error G:\go\src\coke\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: G:\go\src\coke\node_modules\node-sass
Output:
module.js:529
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\go\src\coke\node_modules\node-sass\scripts\install.js:10:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)

--> goimports -w G:\go\src\coke\actions\actions_test.go G:\go\src\coke\actions\app.go G:\go\src\coke\actions\home.go G:\
go\src\coke\actions\home_test.go G:\go\src\coke\actions\render.go G:\go\src\coke\grifts\init.go G:\go\src\coke\main.go
--> goimports -w G:\go\src\coke\actions\actions_test.go G:\go\src\coke\actions\app.go G:\go\src\coke\actions\home.go G:\
go\src\coke\actions\home_test.go G:\go\src\coke\actions\render.go G:\go\src\coke\grifts\init.go G:\go\src\coke\main.go
Usage:
  buffalo new [name] [flags]

Flags:
      --api                  skip all front-end code and configure for an API server
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci] (d
efault "none")
      --db-type string       specify the type of database you want to use [postgres, mysql, sqlite3] (default "postgres"
)
      --docker string        specify the type of Docker file to generate [none, multi, standard] (default "multi")
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
      --skip-yarn            skip to use npm as the asset package manager
  -v, --verbose              verbosely print out the go get commands
      --with-dep             adds github.com/golang/dep to your app

Error: exit status 1

G:\go\src>
```

**Comment by BigJoe01** [comment] 2017-12-13 16:44
This is package-lock.json error or node scripts/install.js failed.
Maybe help  :
remove node_modules
remove package-lock.json
npm cache clean
npm install

**Comment by markbates** [comment] 2017-12-15 20:34
@muloka I'm closing this issue because I believe it's an environmental issue. Also, since Buffalo is on `0.10.2` now, it could be that there was a problem with the `0.9.4` version on Windows. If you are still experiencing this issue, please re-open with more information. Thanks!

**Closed by markbates** 2017-12-15 20:34 UTC
Labels: Help wanted, Windows

**Comment by muloka** [comment] 2017-12-20 16:11
@markbates Still getting an issue on Windows with 0.10.2.

@BigJoe01 Using `npm install` it works, no errors. 

Nonetheless `buffalo new project-name` on Windows defaults to using `yarn install`.

Versions:
```
go 1.9.2 windows/amd64
buffalo 0.10.2
node 8.6.0
yarn 1.3.2
npm 5.3.0
```

**Comment by markbates** [comment] 2017-12-20 16:29
@muloka the default is to use `yarn`. if you don't want to use yarn you have to pass the `--skip-yarn` options to `buffalo new`.

Can you run `buffalo info` from inside of your project and paste the results? Please include which version of Windows. you are running.

Also, can you paste the results from your `buffalo new` command?

I'm not able to reproduce this on Windows at all.

**Comment by muloka** [comment] 2018-01-18 15:09
`G:\go\src\coke> buffalo info
←[33mWARN←[0m[0000] Could not find BUFFALO_PLUGIN_PATH environment variable, default to PATH instead. Consider setting t
he BUFFALO_PLUGIN_PATH variable to speed up loading of plugins and/or to set a custom path for locating them.
### Buffalo Version
v0.10.3

### App Information
Pwd=G:\go\src\coke
Root=G:\go\src\coke
GoPath=G:\go
Name=coke
Bin=bin\coke.exe
PackagePkg=coke
ActionsPkg=coke/actions
ModelsPkg=coke/models
GriftsPkg=coke/grifts
WithPop=false
WithDep=false
WithWebpack=true
WithYarn=false
WithDocker=false
WithGrifts=false

### Go Version
go version go1.9.2 windows/amd64

### Go Env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=G:\go
set GORACE=
set GOROOT=C:\tools\go
set GOTOOLDIR=C:\tools\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\lgalipea\AppData\Local\Temp\go-build0049927
47=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### Node Version
v8.6.0

### NPM Version
5.3.0

### Yarn Version
1.3.2

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
SQLite Not Found

### Dep Version
dep:
 version     : devel
 build date  :
 git hash    :
 go version  : go1.9
 go compiler : gc
 platform    : windows/amd64

### Dep Status
could not find project Gopkg.toml, use dep init to initiate a manifest
Usage:
  buffalo info [flags]

Flags:
  -h, --help   help for info

←[31mERRO←[0m[0006] Error: exit status 1`
