### ISSUE TITLE
`buffalo new` is working unexpectedly

### ISSUE THREAD

**Issue by johndeng** [gobuffalo/buffalo#749] opened 2017-11-11 20:32 UTC
I have using `buffalo new ` to generate a project, but looks generated a incomplete Go project.

```
⋊> ~/P/g/p/s/atlas on master  $ ls
assets       database.yml grifts       models
```

**Comment by markbates** [comment] 2017-11-11 20:39
Can you run the `buffalo info` command and paste the output? Thanks.

**Comment by markbates** [comment] 2017-11-12 02:39
Thinking about it, I think you are having this issue: https://github.com/gobuffalo/buffalo/issues/629

Did you install Buffalo to your `$GOPATH` and then create a new `$GOPATH` to "test" Buffalo? If so, the problem is the templates for generating a new application are in your first `$GOPATH` and they can't be found from you second `$GOPATH`. 

I'm going to close this, since I believe it's a dup of https://github.com/gobuffalo/buffalo/issues/629. If using just one `$GOPATH` doesn't solve your problem, please re-open.

**Closed by markbates** 2017-11-12 02:39 UTC

**Comment by johndeng** [comment] 2017-11-12 08:44
Hi, I tried one `$GOPATH` and it works, but v0.9.5 is not this issues..
