### ISSUE TITLE
A typo in .env that causes site-wide error

### ISSUE THREAD

**Issue by AlhasanIQ** [gobuffalo/buffalo#1077] opened 2018-05-25 12:14 UTC
## Description

  The typo in [.env](https://github.com/gobuffalo/buffalo/blob/354657dfd81584bb82b8b6dff9bb9f6ab22712a8/generators/newapp/templates/dot-env.tmpl#L8) : `SESSIONS_SECRET` instead of `SESSION_SECRET` will misguide newcomers and cause a site-wide error 
`securecookie: hash key is not set`

## Steps to Reproduce the Problem
get a fresh install of buffalo then have your `.env` file as : 
```
SESSIONS_SECRET=loremipsum
```
## Expected Behavior

HTTP 200 on the home handler

## Actual Behavior

HTTP 500 : `securecookie: hash key is not set`

## Info

Unnecessary (not a technical bug).

**Comment by markbates** [comment] 2018-05-25 12:15
Duplicate of #1067

**Closed** 2018-05-25 12:15 UTC
Labels: duplicate
