### ISSUE TITLE
Can't deal with trailing slash?

### ISSUE THREAD

**Issue by dreampuf** [gobuffalo/buffalo#1155] opened 2018-07-02 20:48 UTC
All router's URL that defined with a trailing slash will be eaten. 

```
app.GET("/worker/", func(c buffalo.Context) error {

=>

{\n  \"method\": \"GET\",\n  \"path\": \"/worker\",...
```

**Comment by robbyoconnor** [comment] 2018-07-02 21:41
Dupe of https://github.com/gobuffalo/buffalo/issues/955

**Closed** 2018-07-02 22:18 UTC
