### ISSUE TITLE
'migrate' command in the compiled app binary does not work

### ISSUE THREAD

**Issue by nithin-bose** [gobuffalo/buffalo#2011] opened 2020-07-01 18:14 UTC
### Description
I updated an old buffalo app to v0.16.10.  And the "migrate" in the generated binary does not work. This breaks my existing CI/CD pipeline which uses a multi stage docker build

### Steps to Reproduce the Problem
```
  buffalo build --static -o /bin/app
```
When trying to run migrations with the following:
```
/bin/app migrate
```
It errors out with the following if buffalo is not present (as in multi stage docker image):
```
exec: "buffalo": executable file not found in $PATH
```
or the following if buffalo is present (as in dev):
```
Error: unknown command "migrate" for "buffalo"
```

### Info

<details>

```
-> Go: Checking installation
✓ The `go` executable was found on your system at: /usr/local/go/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.14.4, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /home/vscode/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /usr/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v12.18.0, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /usr/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.14.4, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /usr/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.22.4, meets the minimum requirements.

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
✘ The `mysql` executable could not be found on your system.
For help setting up your MySQL environment please follow the instructions for you platform at:

https://www.mysql.com/downloads/

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.27.2, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /go/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.16.10, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /home/vscode/workspace/job
Root        /home/vscode/workspace/job
GoPath      /home/vscode/go
PackagePkg  job
ActionsPkg  job/actions
ModelsPkg   job/models
GriftsPkg   job/grifts
WithModules true
Name        job
Bin         bin/job
VCS         git
WithPop     false
WithSQLite  false
WithDep     false
WithWebpack false
WithNodeJs  false
WithYarn    false
WithDocker  true
WithGrifts  true
AsWeb       false
AsAPI       true
InApp       true
PackageJSON {map[]}

-> Buffalo: config/buffalo-app.toml
name = "job"
bin = "bin/job"
vcs = "git"
with_pop = false
with_sqlite = false
with_dep = false
with_webpack = false
with_nodejs = false
with_yarn = false
with_docker = true
with_grifts = true
as_web = false
as_api = true

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop"

-> Buffalo: go.mod
module job

go 1.13

require (
        github.com/aws/aws-sdk-go v1.31.4
        github.com/bitly/go-nsq v1.0.7
        github.com/elazarl/goproxy v0.0.0-20191011121108-aa519ddbe484 // indirect
        github.com/gobuffalo/buffalo v0.15.5
        github.com/gobuffalo/buffalo-pop/v2 v2.0.6
        github.com/gobuffalo/envy v1.9.0
        github.com/gobuffalo/mw-contenttype v0.0.0-20190224202710-36c73cc938f3
        github.com/gobuffalo/mw-paramlogger v0.0.0-20190224201358-0d45762ab655
        github.com/gobuffalo/packr/v2 v2.8.0
        github.com/gobuffalo/pop/v5 v5.2.3
        github.com/gobuffalo/suite/v3 v3.0.0
        github.com/gobuffalo/x v0.1.0
        github.com/gofrs/uuid v3.2.0+incompatible
        github.com/golang/snappy v0.0.1 // indirect
        github.com/markbates/grift v1.5.0
        github.com/nsqio/go-nsq v1.0.7 // indirect
        github.com/parnurzeal/gorequest v0.2.16
        github.com/rs/cors v1.7.0
        moul.io/http2curl v1.0.0 // indirect
)
```

</details>

**Comment by cornerot** [comment] 2020-07-01 18:43
You have to use
```
buffalo pop migrate
```
instead of
```
buffalo migrate
```

**Comment by nithin-bose** [comment] 2020-07-02 03:38
@cornerot we could always run migrations from the deployed app, without the buffalo cli being present. This is documented here:
https://gobuffalo.io/en/docs/db/migrations#migrations-once-deployed

**Comment by cornerot** [comment] 2020-07-04 21:18
```
buffalo version
INFO[0000] Buffalo version is: v0.16.1
```

```
./app migrate
[POP] 2020/07/05 00:16:34 sql - SELECT EXISTS (SELECT schema_migration.* FROM schema_migration AS schema_migration WHERE version = $1) | ["20200701174543"]
[POP] 2020/07/05 00:16:34 info - Migrations already up to date, nothing to apply
[POP] 2020/07/05 00:16:34 info - 0.0093 seconds
```

**Comment by paganotoni** [comment] 2020-07-07 12:18
Hey @cornerot @nithin-bose 👋. Thanks for reporting this issue. Will take a look soon and keep you posted.

**Comment by nithin-bose** [comment] 2020-07-08 04:45
@cornerot @paganotoni I was going through the ``buffalo info`` output, go.mod has the following buffalo version:
```
github.com/gobuffalo/buffalo v0.15.5
```
even though the buffalo binary I use is v0.16.1 and I had run `buffalo fix`. 
Could this be a ``buffalo fix`` issue? Shouldn't the version in go.mod be the one I am running v0.16.1 in this case?

**Comment by nithin-bose** [comment] 2020-07-08 05:04
Manually updated go.mod to v0.16.10 now `/bin/app pop migrate` works if buffalo is in the path but  `/bin/app migrate` still fails with `Error: unknown command "migrate" for "buffalo"`

**Comment by stanislas-m** [comment] 2020-07-16 20:44
@nithin-bose do you have a `database.yml` file at the root of your project?

**Comment by nithin-bose** [comment] 2020-07-17 19:07
@stanislas-m yes. When developing, `buffalo pop migrate up` works fine. 

This issue occurs with the compiled app binary. The 2nd stage of the multistage docker file never required the database.yml file. correct?

**Comment by paganotoni** [comment] 2020-09-05 18:04
@nithin-bose this is how I tried to reproduce this one without success:

```
buffalo new --api bufapi && cd bufapi
docker build .
docker run [image id] /bin/app migrate

[POP] 2020/09/05 18:03:02 warn - ignoring file .pop-tmp.md because it does not match the migration file pattern
[POP] 2020/09/05 18:03:02 info - 0.0008 seconds
```

Are there other details you think could help us solve it ? Thanks!

**Comment by nithin-bose** [comment] 2020-09-05 19:30
@paganotoni As mentioned in the comment above (https://github.com/gobuffalo/buffalo/issues/2011#issuecomment-655280586), the project was initially created with buffalo `v0.15.5` and then updated to buffalo `v0.16.1` using `buffalo fix`. Maybe the issue could have happened due to the upgrade. At the time, the project did not use any db so I am not sure if migrate was working on `v0.15.5`.

However I do remember that one of the buffalo `v0.15.*` versions had an issue with migrations due to a packr issue which I had reported on the slack channel. Maybe its related.

**Comment by paganotoni** [comment] 2020-09-06 13:42
Thanks for the clarification @nithin-bose. Just to confirm I'm understanding correctly, do you think this issue is no longer happening in v0.16.x ?

**Comment by nithin-bose** [comment] 2020-09-07 12:16
That issue was fixed in the release immediately after. I do remember recreating the project with the new release. I am pretty sure v0.16.x doesn't have the packr issue as a new project created from v0.16.x does not seem to have any migration issues (as per previous comments).

As for the current issue, after updating the packr version seems to be the latest. @paganotoni do you think the current issue is related to the old issue?

**Comment by paganotoni** [comment] 2020-10-22 13:31
Hey @nithin-bose Thanks for your patience with this one. I'm not sure if its related but I could not reproduce this one on v0.16.15. Are you ok closing this one ?

**Comment by paganotoni** [comment] 2020-10-29 01:38
Could not reproduce this one in v0.16.15 nor in v0.16.16.

**Closed by paganotoni** 2020-10-29 01:38 UTC
