### ISSUE TITLE
No validation in generators

### ISSUE THREAD

**Issue by kamilgregorczyk** [gobuffalo/buffalo#870] opened 2018-01-22 19:05 UTC
I just did
`buffalo g r name,body` and it generated wrong files, it would be good to have 1. Validation 2. A confirm check if we really want to create/roll back it it there were some errors.

**Comment by kamilgregorczyk** [comment] 2018-01-22 19:10
The same for `buffalo g r name body`

**Comment by kamilgregorczyk** [comment] 2018-01-22 19:22
Here's a pastebin https://pastebin.com/E2rk93DS

**Comment by hubyhuby** [comment] 2018-03-10 08:22
A BIG +1 for this feature
From a beginner stand point, you end up doing a lot of what I call "frankenstein apps" to boot with:)
I did maybe 20 buffalo apps just to understand what is working and not working

What I read is that by default Buffalo passes everything he doesn t understand to the underlying database (it is a documented behavior, feature not a bug :) ) 
The net result of the conjunction of : not having warnings + passing everything to the database, is "frankenstein apps"

Then you start to make your own rules of thumbs, it seems that uint doesn t work, that putting some uppercase letter doesn t work sometimes, that sometimes having "_" doesn t work ... (which I am sure all have good reasons)

I see two things that could work  (as @kamilgregorczyk proposed): 
- Validation with Warnings
- If a warning arise a question: "Do you feel lucky ?!"

**Comment by forrest321** [comment] 2018-03-22 19:09
@kamilgregorczyk From the pastebin, line 15 references two files:

> models/name,body.go models/name,body_test.go 

Do those files exist as named? The commas in the filenames are causing the errors that begin on line 16.

**Comment by kamilgregorczyk** [comment] 2018-03-23 10:09
Yes, these we created by buffalo g r name body

**Comment by forrest321** [comment] 2018-03-23 12:36
I would suggest deleting those files and any references to them. While it looks like the filesystems involved are ok with the name, filenames containing commas are against common conventions and will cause untold problems for you going forward.

After a little digging, it looks like an update of your buffalo code will solve the issue.  Pastebin of my test run here:  https://pastebin.com/tbAiPmWJ  Note the version number on line 11: v4.2.2, where your pastebin is using v3.51.1 , also line 11.  

Delete those files containing commas in the name.  Update buffalo with the following:

`get -u github.com/gobuffalo/buffalo/...`

And try your generates again. There have been several fixes and improvements in the code since the version you are using.

**Comment by stanislas-m** [comment] 2019-07-13 11:07
Should be fixed since https://github.com/gobuffalo/pop/pull/231

**Closed by stanislas-m** 2019-07-13 11:07 UTC
Labels: enhancement, help wanted
