### ISSUE TITLE
`package grifts is not in GOROOT` on M1

### ISSUE THREAD

**Issue by rvarun11** [gobuffalo/buffalo#2268] opened 2022-05-15 20:27 UTC
I'm trying to use grift to in my Buffalo project with:
1. `buffalo task list` 
2. `buffalo routes` 

On running the above commands, I'm getting the following error:

```
.grifter/main.go:9:2: package grifts is not in GOROOT (/opt/homebrew/Cellar/go/1.18.2/libexec/src/grifts)
Usage:
  buffalo task [flags]

Aliases:
  task, t, tasks

Flags:
  -h, --help   help for task

ERRO[0000] Error: exit status 1  
```

Go Version: 1.18.2 darwin/arm64

I tried using previous versions of Go as well but the error persisted. 

I've installed Go and Buffalo via brew

**Comment by sio4** [comment] 2022-05-16 11:19
This is a duplicate of https://github.com/gobuffalo/cli/issues/142 (the `buffalo` command is provided by `cli` package.

FYI, the new version of buffalo (v0.18.5) was just shipped with the fix.

**Closed by sio4** 2022-05-16 11:19 UTC
